function g_info
global goose

dy2 = .02; %Abstand zwischen Zeilen
dw1 = .1; %Abstand Txtfelder von links (west)
dw2 = .5; %Abstand der Edits von links
ds = .86; %Abstand des ersten Felds von unten (south)

goose.gui.fig_info = figure('Units','normalized','Position',[.05 .5 .3 .4],'Menubar','None','Name','Info','Numbertitle','Off');
goose.gui.text_info = uicontrol('Style','text','Units','normalized','FontUnits','normalized','Position',[dw1 .1 .8 .8],'FontSize',.035,...
    'String',{'Shortcuts and GUI handling'; ''; 'a:      Analyze...'; 'c:      Analyze current frame'; 'n:      Normalize...'; 't:      Toogle between frames'; 'Esc: Stop analysis / play mode / toggle mode'; '';...
    's:      Save Gooselab project'; 'o (or click on swan):  Load new video'; '';...
    'left arrow: move one frame to the beginning'; 'right arrow: move one frame to the end'; 'right click in time window: Select 2nd toggle frame'; 'drag field in time window: Select time epoch for analysis'; '';...
    'In some cases you may have to click onto the plain figure before shortcuts can be used'}',...
    'HorizontalAlignment','left','BackgroundColor',get(gcf,'Color'));
