function g_info

figure('Units','normalized','Position',[.05 .5 .3 .4],'Menubar','None','Name','Info','Numbertitle','Off');
uicontrol('Style','text','Position',[.1 .1 .8 .8],'FontSize',.035,...
    'String',{...
        'Shortcuts and GUI handling'; '';...
        'a: Analyze...';...
        'c: Analyze current frame';...
        'n: Normalize...';...
        't: Toogle between frames';...
        'Esc: Stop analysis / play mode / toggle mode'; '';...
        's: Save Gooselab project';...
        'o: Load new video'; '';...
        'left arrow: move one frame back';...
        'right arrow: move one frame forward';...
        'right click in time window: Select 2nd toggle frame';...
        'drag field in time window: Select time slice for analysis';...
    }','HorizontalAlignment','left');
